CREATE TABLE IF NOT EXISTS users (id int AUTO_INCREMENT PRIMARY KEY, name varchar(40) NOT NULL UNIQUE, type ENUM('admin','normal') NOT NULL);
CREATE TABLE IF NOT EXISTS categories (id int AUTO_INCREMENT PRIMARY KEY, name VARCHAR(40) NOT NULL UNIQUE);
